---
version: 0.2

phases:
  pre_build:
   commands:
    - $(aws ecr get-login --no-include-email --region us-east-1)


  build:
   commands:
    - docker build -t ad-fargate:latest .
    - docker tag ad-fargate:latest 061034823110.dkr.ecr.us-east-1.amazonaws.com/ad-fargate:latest

  post_build:
   commands:
    - docker push 061034823110.dkr.ecr.us-east-1.amazonaws.com/ad-fargate:latest

artifacts:
 files: imagedefinitions.json 